# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-20.04'

variables:
  dockerId: 'nozzlegear'
  imageName: 'dijon'
  baseImageName: '$(dockerId).azurecr.io/$(imageName)'
  latestImageName: '$(baseImageName):latest'
  buildImageName: '$(baseImageName):$(build.buildId)'

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '20.10.7'
  displayName: 'Install Docker 20.10.7'
- script: docker --version
  displayName: 'Print Docker version'
- script: docker build -t '$(latestImageName)' -t '$(buildImageName)' .
  displayName: 'Build container image'
- bash: |
   # Create a temporary container from the test image and copy the /app/testresults files out
   docker create --name testcontainer $(buildImageName)
   docker cp testcontainer:/app/testresults/testresults.xml .
   cat ./testresults.xml
   docker rm testcontainer 
  failOnStderr: true
  displayName: 'Collect test files'
- task: PublishTestResults@2
  displayName: 'Publish test files'
  inputs:
    testResultsFormat: 'XUnit'
    testResultsFiles: './testresults.xml'
    failTaskOnFailedTests: true
- script: |
    docker login -u $(dockerId) -p $pswd $(dockerId).azurecr.io
    docker push $(baseImageName)
  displayName: 'Push container image to ACR'
  env:
    # Do not pass the acrPassword variable directly to the login script. Instead, use an env variable.
    # https://github.com/MicrosoftDocs/vsts-docs/issues/4113
    pswd: $(acrPassword)
