<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Faqt" Version="5.1.0" />
    <PackageVersion Include="FSharp.Core" Version="11.0.100" />
    <PackageVersion Include="Npgsql" Version="10.0.3" />
    <PackageVersion Include="Npgsql.FSharp" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.KeyPerFile" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.0.10" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="Simple.Migrations" Version="0.9.21" />
    <PackageVersion Include="discord.net" Version="3.20.1" />
    <PackageVersion Include="FSharp.Control.AsyncSeq" Version="4.15.0" />
    <PackageVersion Include="thoth.json.net" Version="12.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.10" />
    <PackageVersion Include="taskbuilder.fs" Version="2.1" />
    <PackageVersion Include="cronos" Version="0.13.0" />
    <PackageVersion Include="TimeZoneConverter" Version="7.2.0" />
    <PackageVersion Include="LazyCache" Version="2.4.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="DotNet.ReproducibleBuilds.Isolated" Version="2.0.5" PrivateAssets="All" />
  </ItemGroup>
</Project>