version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        env_file: .env
        environment:
            COUCH_HOST: "http://db:5984"
        ports:
            - 3000:3000
        depends_on:
            - db
    db:
        image: "couchdb"
        ports:
            - 3001:5984
        logging:
            driver: none
