<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RuntimeIdentifiers>linux-musl-x64;linux-x64;osx-arm64</RuntimeIdentifiers>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Models.fs" />
        <Compile Include="StreamAnnouncements\Models.fs" />
        <Compile Include="StreamAnnouncements\StreamAnnouncementsDatabase.fs" />
        <Compile Include="LogChannels\LogChannelsDatabase.fs" />
        <Compile Include="AffixChannels\Models.fs" />
        <Compile Include="AffixChannels\AffixChannelsDatabase.fs" />
        <Compile Include="MessageReactionGuards\Models.fs" />
        <Compile Include="MessageReactionGuards\MessageReactionGuardsDatabase.fs" />
        <Compile Include="ServiceCollectionExtensions.fs" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Npgsql" />
      <PackageReference Include="Npgsql.FSharp" />
      <PackageReference Include="FSharp.Core" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
      <PackageReference Include="Microsoft.Extensions.Hosting" />
      <PackageReference Include="Microsoft.Extensions.Logging" />
      <PackageReference Include="Microsoft.Extensions.Options" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
      <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Dijon.Shared\Dijon.Shared.fsproj" />
    </ItemGroup>

</Project>
