<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifiers>linux-musl-x64;linux-x64;osx-arm64</RuntimeIdentifiers>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Migrations\Migration_01.fs" />
    <Compile Include="Migrator.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Simple.Migrations" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Dijon.Shared\Dijon.Shared.fsproj" />
  </ItemGroup>
</Project>
